# Regions
- id: "us-east-1"
  name: "US East (N. Virginia)"
  csp: "aws"
- id: "us-west-2"
  name: "US West (Oregon)"
  csp: "aws"
- id: "centralus"
  name: "Central US"
  csp: "azure"
- id: "eastus"
  name: "East US"
  csp: "azure"
- id: "us-central1"
  name: "US Central 1"
  csp: "gcp"
- id: "europe-west1"
  name: "Europe West 1"
  csp: "gcp"
